### PR TITLE
Update to v5.1.1

### PR DESCRIPTION
**Pull request by synapticarbors**
Also:

- Add myself as a co-maintainer
- Switch to `noarch: python`

### CODE REVIEW

**Comment by synapticarbors** [comment]
@holtgrewe - if you get a chance, could you please look at this pull request?

**Comment by synapticarbors** [comment]
@holtgrewe - Just wanted to bump this PR again. 

@jakirkham - If this doesn't get reviewed soon, are you able to act on it?

**Comment by holtgrewe** [comment]
Looks good to me.

**Comment by synapticarbors** [comment]
If it looks good, could you please merge the pull request. Thanks.

**Pull request merged**
