### PR TITLE
sync with AnacondaRecipes

### PR DESCRIPTION
**Pull request by jjhelmus**
* switch to host requirements as recommended when using conda build 3
* add description
* additional import test

### CODE REVIEW

**Comment by synapticarbors** [comment]
should the build number be incremented?

**Comment by jjhelmus** [comment]
> should the build number be incremented?

The only change in the contents of the package should be the meta.yaml file itself so I did not bump the build number.

**Comment by synapticarbors** [comment]
I'm just basing this off of having seen the bot that updates stuff like `build` -> `host` has been bumping the build number. I'm not sure if it's entirely necessary.

**Comment by synapticarbors** [comment]
For example: https://github.com/conda-forge/falcon-feedstock/pull/8/files#diff-e178b687b10a71a3348107ae3154e44cR14

**Comment by jjhelmus** [comment]
I'm not certain a build number increment is needed but I put one in anyway.

**Pull request merged**
